# Minimal secrets for testing
OPENROUTER_API_KEY = "test_key"
GOOGLE_MAPS_API_KEY = "test_key"
STRIPE_TEST_SECRET_KEY = "sk_test_fake"
STRIPE_TEST_PUBLISHABLE_KEY = "pk_test_fake"
STRIPE_LIVE_SECRET_KEY = "sk_live_fake"
STRIPE_LIVE_PUBLISHABLE_KEY = "pk_live_fake"